In [13]:
import torch
BATCH, S = 1, 7
dummy = torch.rand((BATCH, 4, S, S))

In [14]:
print(dummy)

tensor([[[[0.4417, 0.4776, 0.3990, 0.0390, 0.6481, 0.5397, 0.5820],
          [0.1364, 0.6774, 0.8136, 0.3350, 0.8182, 0.0661, 0.3687],
          [0.4825, 0.7669, 0.4066, 0.6342, 0.2155, 0.4720, 0.5390],
          [0.9171, 0.5215, 0.2827, 0.1803, 0.3033, 0.4955, 0.2588],
          [0.2835, 0.5315, 0.3201, 0.1884, 0.9311, 0.6238, 0.6709],
          [0.0054, 0.8194, 0.7876, 0.8835, 0.5688, 0.2217, 0.0046],
          [0.0277, 0.5239, 0.0420, 0.9627, 0.6403, 0.6589, 0.2064]],

         [[0.8337, 0.7150, 0.7901, 0.2390, 0.1817, 0.1161, 0.3663],
          [0.9230, 0.6770, 0.9500, 0.4609, 0.1935, 0.9214, 0.7233],
          [0.9979, 0.3825, 0.4147, 0.0977, 0.4941, 0.5700, 0.9691],
          [0.4572, 0.9036, 0.0696, 0.1606, 0.8026, 0.5524, 0.6611],
          [0.5814, 0.8345, 0.4272, 0.4142, 0.2378, 0.3261, 0.4874],
          [0.9129, 0.9963, 0.1610, 0.3666, 0.0539, 0.9030, 0.5483],
          [0.5270, 0.5815, 0.2457, 0.8055, 0.9814, 0.9919, 0.5216]],

         [[0.5997, 0.4512, 0.2554, 0.3473, 0

In [21]:
print(1 - dummy[:, 0:1, :, :])

tensor([[[[0.5583, 0.5224, 0.6010, 0.9610, 0.3519, 0.4603, 0.4180],
          [0.8636, 0.3226, 0.1864, 0.6650, 0.1818, 0.9339, 0.6313],
          [0.5175, 0.2331, 0.5934, 0.3658, 0.7845, 0.5280, 0.4610],
          [0.0829, 0.4785, 0.7173, 0.8197, 0.6967, 0.5045, 0.7412],
          [0.7165, 0.4685, 0.6799, 0.8116, 0.0689, 0.3762, 0.3291],
          [0.9946, 0.1806, 0.2124, 0.1165, 0.4312, 0.7783, 0.9954],
          [0.9723, 0.4761, 0.9580, 0.0373, 0.3597, 0.3411, 0.7936]]]])


In [7]:
print(dummy[...,:,0,0])

tensor([[0.6767, 0.9598, 0.9950, 0.8599]])


In [64]:
A = torch.randint(low = 0, high = 10, size=(BATCH, 4, 7, 7))
B = torch.rand(BATCH, 4, 7, 7)

In [38]:
print(A[:,0:1,:,:])

tensor([[[[4, 0, 6, 9, 5, 0, 2],
          [9, 7, 2, 9, 0, 9, 5],
          [0, 7, 4, 2, 0, 7, 0],
          [6, 8, 1, 4, 1, 1, 3],
          [9, 6, 5, 3, 4, 0, 7],
          [7, 6, 5, 4, 4, 5, 2],
          [7, 7, 7, 5, 8, 3, 8]]]])


In [42]:
C = A[:, 0:1, :, :] * B[:, 0:1, :, :]

In [43]:
print(C)

tensor([[[[ 8,  0,  0, 54, 10,  0, 18],
          [63, 56, 12, 81,  0, 63,  5],
          [ 0,  0, 20, 12,  0,  0,  0],
          [24, 48,  7,  8,  7,  2, 24],
          [72, 12, 20, 21, 24,  0, 42],
          [ 7, 42,  5,  4,  4, 15,  6],
          [63, 21, 14, 15, 16,  6, 40]]]])


In [44]:
C.shape

torch.Size([1, 1, 7, 7])

In [ ]:
def cvtCellCoord2ImgCoord(in_tensor, S):
    device = in_tensor.device
    i = torch.arange(S, device=device).view(1, S, 1, 1)
    j = torch.arange(S, device=device).view(1, 1, S, 1)

    x_center = (j + in_tensor[..., 0:1]) / S
    y_center = (i + in_tensor[..., 1:2]) / S

    w = in_tensor[..., 2:3]
    h = in_tensor[..., 3:4]

    return torch.cat([x_center, y_center, w, h], dim = -1)

In [49]:
a = torch.arange(7)

In [50]:
print(a)

tensor([0, 1, 2, 3, 4, 5, 6])


In [51]:
b = a.view(1,1,7,1)

In [48]:
print((10 - A[:,0:1, :, :]) * B[:, 0:4, :, :])


tensor([[[[12, 30,  0,  6, 10, 90, 72],
          [ 7, 24, 48,  9, 30,  7,  5],
          [50,  0, 30, 48, 10,  0, 10],
          [16, 12, 63, 12, 63, 18, 56],
          [ 8,  8, 20, 49, 36, 50, 18],
          [ 3, 28,  5,  6,  6, 15, 24],
          [27,  9,  6, 15,  4, 14, 10]],

         [[42, 80, 16,  5, 10, 40, 32],
          [ 8, 12,  8,  9, 90,  0,  0],
          [ 0, 21, 24, 24, 10, 15, 90],
          [28, 18, 45, 42, 63, 54, 56],
          [ 6,  8, 45, 21, 36, 70,  6],
          [15,  4, 30, 42,  6, 15,  8],
          [24,  9,  3, 20,  0,  0, 10]],

         [[42, 50,  0,  5, 40, 90, 40],
          [ 2,  9, 72,  8, 70,  8,  5],
          [20, 15, 54, 16, 10, 12, 80],
          [32,  4, 45, 12, 63, 54, 21],
          [ 9,  4, 25, 35,  0, 60, 18],
          [ 9, 28, 25,  0, 42, 35, 24],
          [ 3,  3, 24, 10,  8, 56, 12]],

         [[ 6, 60,  0,  1, 45,  0,  8],
          [ 9,  6, 40,  7, 40,  4, 25],
          [70, 12,  6, 56, 80,  6, 40],
          [20, 18, 45, 54, 54, 27,

In [52]:
print(b)

tensor([[[[0],
          [1],
          [2],
          [3],
          [4],
          [5],
          [6]]]])


In [78]:
c = torch.arange(7).view(1,1,7,1)

In [67]:
print(B)

tensor([[[[0.0841, 0.9591, 0.6324, 0.0687, 0.6820, 0.5613, 0.3101],
          [0.2593, 0.8805, 0.1374, 0.9366, 0.6614, 0.1356, 0.1163],
          [0.2565, 0.3796, 0.7860, 0.5776, 0.9063, 0.2203, 0.6409],
          [0.3886, 0.1897, 0.0280, 0.3683, 0.2793, 0.4913, 0.8328],
          [0.3045, 0.2264, 0.4216, 0.3729, 0.4751, 0.5577, 0.8874],
          [0.1273, 0.6262, 0.1426, 0.7762, 0.1339, 0.5223, 0.2386],
          [0.7142, 0.6099, 0.1680, 0.4255, 0.9117, 0.0693, 0.0680]],

         [[0.0724, 0.1744, 0.7359, 0.6219, 0.5081, 0.2704, 0.5516],
          [0.5207, 0.5644, 0.7309, 0.5707, 0.4969, 0.7865, 0.6920],
          [0.4413, 0.8082, 0.7849, 0.8841, 0.0456, 0.3482, 0.9610],
          [0.1679, 0.4745, 0.3766, 0.9922, 0.8432, 0.3811, 0.9983],
          [0.9834, 0.2838, 0.1274, 0.9948, 0.7461, 0.1455, 0.0107],
          [0.5168, 0.5050, 0.6104, 0.3870, 0.4314, 0.2166, 0.5738],
          [0.3303, 0.3356, 0.8573, 0.9212, 0.3758, 0.5725, 0.2615]],

         [[0.9456, 0.6858, 0.4834, 0.1837, 0

In [57]:
c_b = torch.arange(7).view(1,1,1,7)

In [79]:
print(c)

tensor([[[[0],
          [1],
          [2],
          [3],
          [4],
          [5],
          [6]]]])


In [58]:
print(c_b)

tensor([[[[0, 1, 2, 3, 4, 5, 6]]]])


In [80]:
(c + B[:,0:2,:,:]) / 7

tensor([[[[0.0120, 0.1370, 0.0903, 0.0098, 0.0974, 0.0802, 0.0443],
          [0.1799, 0.2686, 0.1625, 0.2767, 0.2373, 0.1622, 0.1595],
          [0.3224, 0.3399, 0.3980, 0.3682, 0.4152, 0.3172, 0.3773],
          [0.4841, 0.4557, 0.4326, 0.4812, 0.4685, 0.4988, 0.5475],
          [0.6149, 0.6038, 0.6317, 0.6247, 0.6393, 0.6511, 0.6982],
          [0.7325, 0.8037, 0.7347, 0.8252, 0.7334, 0.7889, 0.7484],
          [0.9592, 0.9443, 0.8811, 0.9179, 0.9874, 0.8670, 0.8669]],

         [[0.0103, 0.0249, 0.1051, 0.0888, 0.0726, 0.0386, 0.0788],
          [0.2172, 0.2235, 0.2473, 0.2244, 0.2138, 0.2552, 0.2417],
          [0.3488, 0.4012, 0.3978, 0.4120, 0.2922, 0.3355, 0.4230],
          [0.4526, 0.4964, 0.4824, 0.5703, 0.5490, 0.4830, 0.5712],
          [0.7119, 0.6120, 0.5896, 0.7135, 0.6780, 0.5922, 0.5730],
          [0.7881, 0.7864, 0.8015, 0.7696, 0.7759, 0.7452, 0.7963],
          [0.9043, 0.9051, 0.9796, 0.9887, 0.9108, 0.9389, 0.8945]]]])

In [81]:
(c_b + B[:,0:2,:,:]) / 7

tensor([[[[0.0120, 0.2799, 0.3761, 0.4384, 0.6689, 0.7945, 0.9014],
          [0.0370, 0.2686, 0.3053, 0.5624, 0.6659, 0.7337, 0.8738],
          [0.0366, 0.1971, 0.3980, 0.5111, 0.7009, 0.7458, 0.9487],
          [0.0555, 0.1700, 0.2897, 0.4812, 0.6113, 0.7845, 0.9761],
          [0.0435, 0.1752, 0.3459, 0.4818, 0.6393, 0.7940, 0.9839],
          [0.0182, 0.2323, 0.3061, 0.5395, 0.5906, 0.7889, 0.8912],
          [0.1020, 0.2300, 0.3097, 0.4894, 0.7017, 0.7242, 0.8669]],

         [[0.0103, 0.1678, 0.3908, 0.5174, 0.6440, 0.7529, 0.9359],
          [0.0744, 0.2235, 0.3901, 0.5101, 0.6424, 0.8266, 0.9560],
          [0.0630, 0.2583, 0.3978, 0.5549, 0.5779, 0.7640, 0.9944],
          [0.0240, 0.2106, 0.3395, 0.5703, 0.6919, 0.7687, 0.9998],
          [0.1405, 0.1834, 0.3039, 0.5707, 0.6780, 0.7351, 0.8587],
          [0.0738, 0.2150, 0.3729, 0.4839, 0.6331, 0.7452, 0.9391],
          [0.0472, 0.1908, 0.4082, 0.5602, 0.6251, 0.7961, 0.8945]]]])

In [5]:
import torch
A = torch.randint(low = 0, high = 10, size=(1, 4, 7, 7))
B = torch.randint(low = 0, high = 10, size=(1, 4, 7, 7))

In [6]:
A

tensor([[[[8, 1, 0, 5, 5, 2, 6],
          [2, 2, 2, 8, 0, 6, 5],
          [2, 2, 8, 4, 6, 9, 6],
          [4, 1, 3, 5, 1, 5, 7],
          [4, 0, 6, 7, 4, 1, 2],
          [5, 8, 6, 2, 9, 7, 1],
          [4, 5, 0, 6, 0, 8, 7]],

         [[9, 0, 0, 8, 3, 2, 0],
          [7, 6, 7, 2, 1, 7, 9],
          [1, 6, 3, 5, 1, 5, 8],
          [0, 4, 5, 1, 6, 8, 0],
          [2, 4, 2, 0, 7, 7, 7],
          [7, 6, 7, 1, 9, 3, 8],
          [5, 2, 3, 8, 2, 2, 0]],

         [[1, 1, 1, 0, 7, 7, 8],
          [5, 9, 2, 3, 0, 7, 0],
          [0, 4, 5, 6, 7, 0, 5],
          [5, 7, 9, 9, 8, 0, 3],
          [2, 0, 1, 7, 2, 8, 4],
          [0, 5, 7, 4, 0, 9, 9],
          [9, 5, 7, 5, 8, 0, 2]],

         [[7, 7, 0, 9, 5, 0, 1],
          [4, 1, 0, 4, 5, 4, 5],
          [2, 5, 7, 1, 7, 8, 4],
          [5, 3, 6, 9, 3, 2, 8],
          [2, 6, 4, 5, 3, 8, 6],
          [3, 9, 4, 4, 1, 4, 6],
          [2, 9, 8, 2, 9, 2, 1]]]])

In [7]:
B

tensor([[[[1, 0, 6, 8, 0, 8, 3],
          [7, 1, 8, 0, 5, 7, 8],
          [5, 0, 7, 1, 4, 6, 8],
          [9, 9, 1, 3, 5, 2, 4],
          [7, 0, 6, 2, 2, 1, 1],
          [5, 7, 0, 9, 4, 8, 5],
          [2, 9, 3, 2, 6, 6, 7]],

         [[3, 0, 1, 1, 7, 5, 3],
          [1, 7, 9, 9, 0, 4, 9],
          [6, 4, 6, 1, 3, 2, 8],
          [0, 8, 8, 4, 6, 0, 6],
          [1, 2, 9, 1, 4, 4, 0],
          [0, 0, 0, 8, 3, 0, 0],
          [1, 3, 5, 1, 2, 6, 4]],

         [[7, 4, 4, 0, 7, 1, 8],
          [0, 0, 6, 3, 5, 8, 5],
          [5, 9, 6, 7, 3, 6, 2],
          [8, 4, 7, 6, 7, 8, 1],
          [7, 1, 9, 6, 8, 6, 9],
          [8, 9, 8, 3, 5, 9, 6],
          [3, 4, 1, 5, 5, 7, 7]],

         [[2, 2, 3, 2, 7, 9, 9],
          [6, 1, 2, 9, 2, 4, 5],
          [2, 9, 5, 7, 2, 9, 7],
          [5, 0, 5, 2, 7, 3, 5],
          [9, 3, 1, 8, 2, 5, 5],
          [1, 5, 3, 4, 3, 0, 3],
          [2, 6, 4, 4, 2, 2, 7]]]])

In [8]:
torch.max(A,B)

tensor([[[[8, 1, 6, 8, 5, 8, 6],
          [7, 2, 8, 8, 5, 7, 8],
          [5, 2, 8, 4, 6, 9, 8],
          [9, 9, 3, 5, 5, 5, 7],
          [7, 0, 6, 7, 4, 1, 2],
          [5, 8, 6, 9, 9, 8, 5],
          [4, 9, 3, 6, 6, 8, 7]],

         [[9, 0, 1, 8, 7, 5, 3],
          [7, 7, 9, 9, 1, 7, 9],
          [6, 6, 6, 5, 3, 5, 8],
          [0, 8, 8, 4, 6, 8, 6],
          [2, 4, 9, 1, 7, 7, 7],
          [7, 6, 7, 8, 9, 3, 8],
          [5, 3, 5, 8, 2, 6, 4]],

         [[7, 4, 4, 0, 7, 7, 8],
          [5, 9, 6, 3, 5, 8, 5],
          [5, 9, 6, 7, 7, 6, 5],
          [8, 7, 9, 9, 8, 8, 3],
          [7, 1, 9, 7, 8, 8, 9],
          [8, 9, 8, 4, 5, 9, 9],
          [9, 5, 7, 5, 8, 7, 7]],

         [[7, 7, 3, 9, 7, 9, 9],
          [6, 1, 2, 9, 5, 4, 5],
          [2, 9, 7, 7, 7, 9, 7],
          [5, 3, 6, 9, 7, 3, 8],
          [9, 6, 4, 8, 3, 8, 6],
          [3, 9, 4, 4, 3, 4, 6],
          [2, 9, 8, 4, 9, 2, 7]]]])

In [1]:
a = [[1,2,3],[4,6,7]]

In [2]:
import torch

In [4]:
torch.tensor(a).shape

torch.Size([2, 3])

In [1]:
import torch

A = torch.tensor([[[1,0],[1,1]], [[0,1],[1,0]]])
B = torch.tensor([[[1,1],[0,1]], [[1,0],[1,1]]])

In [4]:
A

tensor([[[1, 0],
         [1, 1]],

        [[0, 1],
         [1, 0]]])

In [5]:
B

tensor([[[1, 1],
         [0, 1]],

        [[1, 0],
         [1, 1]]])

In [2]:
mask = (A == 1) & (B == 1)

In [3]:
mask

tensor([[[ True, False],
         [False,  True]],

        [[False, False],
         [ True, False]]])

In [6]:
result = mask.to(torch.int)

In [7]:
result

tensor([[[1, 0],
         [0, 1]],

        [[0, 0],
         [1, 0]]], dtype=torch.int32)